spring:
  config:
    activate:
      on-profile: prod

#  datasource:
#    url: jdbc:postgresql://${PGHOST}:${PGPORT}/${POSTGRES_DB}
#    username: ${PGUSER}
#    password: ${PGPASSWORD}
#    driver-class-name: org.postgresql.Driver
  datasource:
    url: jdbc:postgresql://postgres.railway.internal:5432/railway
    username: postgres
    password: FrYXcLvdcsVDMkdZAZynJtRHfVDRVThz
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  session:
    store-type: jdbc
    jdbc:
      initialize-schema: always  # 또는 embedded

  server:
    port: ${PORT:8080}

  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
file:
  upload-dir: /tmp/uploads
