spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/churchdb
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  session:
    store-type: jdbc                   # JDBC 기반 세션 사용
    jdbc:
      initialize-schema: always        # DB에 없으면 테이블 생성
server:
  port: 8080
