#spring:
#  datasource:
#    url: jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}
#    username: ${PGUSER}
#    password: ${PGPASSWORD}
#    driver-class-name: org.postgresql.Driver
spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/churchdb
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  session:
    store-type: none

#    store-type: jdbc
#    jdbc:
#      initialize-schema: always  # 또는 embedded

  server:
    port : 8080
#    port: ${PORT:8080}

  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

file:
  upload-dir: /tmp/uploads
